# Generated by Django 3.1.3 on 2020-11-12 19:25

from django.db import migrations, models
import hrm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=hrm.models.Users.upload_photo)),
                ('reume', models.ImageField(blank=True, null=True, upload_to=hrm.models.Users.upload_file)),
            ],
        ),
    ]
